---
apiVersion: v1
kind: Service
metadata:
  name: petstore-service
spec:
  selector:
    app: petstore-service
  ports:
    - name: http
      protocol: TCP
      port: 6742
      targetPort: 6742
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-service
  labels:
    app: petstore-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore-service
  template:
    metadata:
      labels:
        app: petstore-service
    spec:
      containers:
        - name: service
          image: petstore:latest

